name: Frontend CI

on:
  push:
    paths:
      - 'FRONTEND_GS/**'
  pull_request:
    paths:
      - 'FRONTEND_GS/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SESSION_SECRET: test_secret_key

    defaults:
      run:
        working-directory: FRONTEND_GS
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: FRONTEND_GS/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
